server:
  port: 8041

nacos-server-addr: localhost:8848

spring:
  application:
    name: user-center

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-server-addr}
        cluster-name: CDC
        metadata:
          version: v1

rocketmq:
  name-server: 127.0.0.1:9876

---
spring:
  profiles: dev

---
spring:
  profiles: prod